# syntax=docker/dockerfile:1

ARG RUBY_VERSION=3.2.11
FROM docker.io/library/ruby:${RUBY_VERSION}-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      bash \
      build-essential \
      curl \
      git \
      libsqlite3-dev \
      libvips \
      libyaml-dev \
      pkg-config \
      sqlite3 && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle \
    BUNDLE_WITHOUT=

COPY Gemfile Gemfile.lock ./
COPY vendor ./vendor

RUN bundle install

COPY . .

CMD ["bash"]